name: 'ssh'
description: 'get an ssh terminal'
inputs:
  ssh_key:
    description: 'private key'
    required: true
  key_file:
    description: 'ssh key file name'
    default: 'id_rsa'
    required: false
runs:
  using: "composite"
  steps: 
    - name: keys
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/${{ inputs.key_file }}
        chmod 400 ~/.ssh/${{ inputs.key_file }}
        chmod 700 ~/.ssh
        cat << EOF > ~/.ssh/config
        Host *
            ServerAliveInterval 60
            StrictHostKeyChecking no

        Host github.com
            User git
            Port 22
            Hostname github.com
            TCPKeepAlive yes
            IdentitiesOnly yes
        EOF
