name: linux
on:
  workflow_dispatch:
    inputs:
      architecture:
        type: choice
        description: "Select architecture"
        options:
          - x86_64
          - aarch64
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ github.event.inputs.architecture == 'x86_64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: miraclx/fastsys/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: fastsys
      - uses: actions/checkout@v2
      - run: source script-linux.sh
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@master
