name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: miraclx/fastsys/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
        authorized_keys: ${{ secrets.AUTHORIZED_KEYS }}
    - uses: actions/checkout@v2
    - run: source script-linux.sh
    - name: Install dependencies
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo apt-get install ripgrep ./cloudflared-linux-amd64.deb
    - name: Launch tunnel
      run: |
        tmux new -Ads d3v -n first \
          cloudflared tunnel --url ssh://localhost:22 --metrics localhost:5642 \; \
          neww
        echo "Entering main loop"
        while true; do
          if URL=$(curl -s http://localhost:5642/metrics | rg 'cloudflared_tunnel_user_hostnames_counts\{userHostname="https://(.+)"\}.+' -r '$1')
          then echo "$ ssh $URL"
          fi
          sleep 10
        done
