name: linux
on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        description: "Select machine"
        options:
          - ubuntu-24.04-arm
          - ubuntu-24.04
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ github.event.inputs.runs-on }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: miraclx/fastsys/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: fastsys
      - uses: actions/checkout@v2
      - run: source script-linux.sh
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@master
